# bot/constants.py

WAITING_API_KEY = 0
WAITING_API_SECRET = 1

WAITING_STRATEGY_NAME = 2
WAITING_STRATEGY_COINS = 3
WAITING_STRATEGY_AMOUNT = 4

WAITING_SIGNAL_SYMBOL = 5
WAITING_INDICATOR_CHOICE = 6
WAITING_INDICATOR_SYMBOL = 7

WAITING_TIMEFRAME_CHOICE = 8
WAITING_GRAPH_CONFIRMATION = 9

# Constants for technical indicators
SMA_FAST_PERIOD = 20
SMA_SLOW_PERIOD = 50
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30